create or replace TABLE STAGGING.CONFIG.EXTRACTION_STATUS (
	DATABASE_NAME VARCHAR(16777216),
	TYPE VARCHAR(16777216),
	IS_EXTRACTION_COMPLETE VARCHAR(16777216)
);--to track extraction is happening or not (Used in Gold Layer Notebooks)

create or replace TABLE STAGGING.CONFIG.LAST_RUN_TIMESTAMP (
	SCHEMA_NAME VARCHAR(16777216) NOT NULL,
	TABLE_NAME VARCHAR(16777216) NOT NULL,
	INSERT_TIMESTAMP TIMESTAMP_TZ(9),
	primary key (SCHEMA_NAME, TABLE_NAME)
);--For Merge Statement(Used in PROC)

create or replace TABLE STAGGING.CONFIG.PARTITION_TABLE (
	DATABASE_NAME VARCHAR(16777216),
	TABLE_NAME VARCHAR(16777216),
	PARTITION_COL VARCHAR(16777216)
);--For Merge statement (Primary Key of Batch Table)

create or replace TABLE STAGGING.CONFIG.STREAM_PARTITION_TABLE (
	DATABASE_NAME VARCHAR(16777216),
	TABLE_NAME VARCHAR(16777216),
	PARTITION_COL VARCHAR(16777216)
);----For Merge statement (Primary Key of Stream Table)